# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "js-beautify"
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hbt"]
  s.date = "2012-06-22"
  s.description = "Gem for js-beautify"
  s.email = "hassenbentanfous@gmail.com"
  s.executables = ["js-beautify"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/js-beautify",
    "init.sh",
    "js-beautify-copy/.gitmodules",
    "js-beautify-copy/Makefile",
    "js-beautify-copy/README.md",
    "js-beautify-copy/attic/beautify-cl/beautify-cl.js",
    "js-beautify-copy/attic/bin/beautify_js",
    "js-beautify-copy/attic/opera-userscript/beautifier.js",
    "js-beautify-copy/attic/opera-userscript/make_opera_userscript.sh",
    "js-beautify-copy/attic/qtscript/jsbeautify.cpp",
    "js-beautify-copy/attic/qtscript/jsbeautify.pro",
    "js-beautify-copy/attic/qtscript/jsbeautify.qrc",
    "js-beautify-copy/attic/qtscript/readme.txt",
    "js-beautify-copy/attic/readme.txt",
    "js-beautify-copy/attic/unmaintained/bbedit/jsBeautify_BBED.scpt",
    "js-beautify-copy/attic/unmaintained/c-sharp/JSBeautify.cs",
    "js-beautify-copy/attic/v8/README.txt",
    "js-beautify-copy/attic/v8/beautify.h",
    "js-beautify-copy/attic/v8/jsbeautify.cpp",
    "js-beautify-copy/beautify-css.js",
    "js-beautify-copy/beautify-html.js",
    "js-beautify-copy/beautify.js",
    "js-beautify-copy/favicon.png",
    "js-beautify-copy/index.html",
    "js-beautify-copy/jquery/jquery.cookie.js",
    "js-beautify-copy/jquery/jquery.js",
    "js-beautify-copy/license.txt",
    "js-beautify-copy/php/jsbeautifier.php",
    "js-beautify-copy/php/test.php",
    "js-beautify-copy/python/MANIFEST.in",
    "js-beautify-copy/python/js-beautify",
    "js-beautify-copy/python/js-beautify-profile",
    "js-beautify-copy/python/js-beautify-test",
    "js-beautify-copy/python/jsbeautifier/__init__.py",
    "js-beautify-copy/python/jsbeautifier/tests/__init__.py",
    "js-beautify-copy/python/jsbeautifier/tests/testindentation.py",
    "js-beautify-copy/python/jsbeautifier/tests/testjsbeautifier.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/README.specs.mkd",
    "js-beautify-copy/python/jsbeautifier/unpackers/__init__.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/evalbased.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/javascriptobfuscator.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/myobfuscate.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/packer.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/__init__.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/test-myobfuscate-input.js",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/test-myobfuscate-output.js",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/test-packer-62-input.js",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/test-packer-non62-input.js",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/testjavascriptobfuscator.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/testmyobfuscate.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/testpacker.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/tests/testurlencode.py",
    "js-beautify-copy/python/jsbeautifier/unpackers/urlencode.py",
    "js-beautify-copy/python/setup.py",
    "js-beautify-copy/tests/beautify-tests.js",
    "js-beautify-copy/tests/run-tests",
    "js-beautify-copy/tests/sanitytest.js",
    "js-beautify-copy/unpackers/javascriptobfuscator_unpacker.js",
    "js-beautify-copy/unpackers/myobfuscate_unpacker.js",
    "js-beautify-copy/unpackers/p_a_c_k_e_r_unpacker.js",
    "js-beautify-copy/unpackers/urlencode_unpacker.js",
    "lib/js-beautify.rb",
    "test/helper.rb",
    "test/test_js-beautify.rb",
    "update.sh"
  ]
  s.homepage = "http://github.com/hbt/js-beautify-gem"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Gem for js-beautify"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

